[versions]
androidx-core = "1.15.0"
androidx-appcompat = "1.7.0"
androidx-recyclerview = "1.3.2"
material = "1.12.0"
paraphrase = "0.4.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
material = { module = "com.google.android.material:material", version.ref = "material" }
paraphrase-runtime = { module = "app.cash.paraphrase:paraphrase-runtime", version.ref = "paraphrase" }

[plugins]
paraphrase = { id = "app.cash.paraphrase", version.ref = "paraphrase" }
