[versions]
agp = "8.13.2"
spotless = "8.1.0"
ktlint = "1.0.1"
kotest = "6.0.7"
dokka = "2.1.0"
nmcp = "1.3.0"
androidx-core = "1.15.0"
androidx-appcompat = "1.7.0"
material = "1.12.0"
paraphrase = "0.4.1"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
material = { module = "com.google.android.material:material", version.ref = "material" }
paraphrase-runtime = { module = "app.cash.paraphrase:paraphrase-runtime", version.ref = "paraphrase" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
paraphrase = { id = "app.cash.paraphrase", version.ref = "paraphrase" }
